version: 2.1
orbs:
  ios: wordpress-mobile/ios@1.0
  git: wordpress-mobile/git@1.0
commands:
  fix-image:
    steps:
      - run:
          name: Fix CI Image
          command: |
            # Add `/usr/local/bin` to the Xcode 11.2 image's $PATH in order to be able to use dependencies
            if [ $(echo $PATH | ruby -e "puts Kernel.gets.include?('/usr/local/bin')") != "true" ]; then
              echo 'export PATH=/usr/local/bin:$PATH' >> $BASH_ENV
              echo "Manually added `/usr/local/bin` to the $PATH:"
              echo $PATH
            fi
            chruby ruby-2.6.6
            gem install bundler
jobs:
  build:
    executor:
      name: ios/default
      xcode-version: "12.0.0"
    steps:
      - fix-image
      - git/shallow-checkout
      - ios/install-dependencies:
          bundle-install: true
          bundler-working-directory: KanvasCameraExample
          pod-install: true
          cocoapods-working-directory: KanvasCameraExample
      - run:
          name: Pod Install
          when: always
          working_directory: ./KanvasCameraExample
          command: bundle exec pod install
      - ios/test:
          xcode-version: 11.2.1
          workspace: KanvasCameraExample/KanvasCameraExample.xcworkspace
          scheme: KanvasCameraExample
          device: iPhone 8
          ios-version: "14.0"
      - run:
          name: Zip failed diffs
          when: always
          working_directory: ./KanvasCameraExample/KanvasCameraExampleTests
          command: zip -r diffoutput.zip FailureDiffs || true
      - store_artifacts:
          name: Save diffs
          path: KanvasCameraExample/KanvasCameraExampleTests/diffoutput.zip
          destination: testresults
      - ios/save-xcodebuild-artifacts:
          result-bundle-path: build/results
